[workspace]
members = ["crates/gatekeeper-core", "crates/gatekeeper-ffi"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-2.0-only"
repository = "https://github.com/srueegger/me.rueegger.gatekeeper"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
